# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/Code/Project/catbing_chat/tinyllm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/Code/Project/catbing_chat/tinyllm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/Code/Project/catbing_chat/tinyllm/CMakeFiles /data/Code/Project/catbing_chat/tinyllm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/Code/Project/catbing_chat/tinyllm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ggml

# Build rule for target.
ggml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml
.PHONY : ggml

# fast build rule for target.
ggml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/build
.PHONY : ggml/fast

#=============================================================================
# Target rules for targets named ggml_static

# Build rule for target.
ggml_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml_static
.PHONY : ggml_static

# fast build rule for target.
ggml_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml_static.dir/build.make CMakeFiles/ggml_static.dir/build
.PHONY : ggml_static/fast

#=============================================================================
# Target rules for targets named ggml_shared

# Build rule for target.
ggml_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml_shared
.PHONY : ggml_shared

# fast build rule for target.
ggml_shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml_shared.dir/build.make CMakeFiles/ggml_shared.dir/build
.PHONY : ggml_shared/fast

#=============================================================================
# Target rules for targets named llama

# Build rule for target.
llama: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llama
.PHONY : llama

# fast build rule for target.
llama/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama.dir/build.make CMakeFiles/llama.dir/build
.PHONY : llama/fast

#=============================================================================
# Target rules for targets named llama_static

# Build rule for target.
llama_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llama_static
.PHONY : llama_static

# fast build rule for target.
llama_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_static.dir/build.make CMakeFiles/llama_static.dir/build
.PHONY : llama_static/fast

#=============================================================================
# Target rules for targets named llama_shared

# Build rule for target.
llama_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llama_shared
.PHONY : llama_shared

# fast build rule for target.
llama_shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_shared.dir/build.make CMakeFiles/llama_shared.dir/build
.PHONY : llama_shared/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f examples/server/CMakeFiles/server.dir/build.make examples/server/CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named binding

# Build rule for target.
binding: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 binding
.PHONY : binding

# fast build rule for target.
binding/fast:
	$(MAKE) $(MAKESILENT) -f examples/binding/CMakeFiles/binding.dir/build.make examples/binding/CMakeFiles/binding.dir/build
.PHONY : binding/fast

src/common/common.o: src/common/common.cpp.o
.PHONY : src/common/common.o

# target to build an object file
src/common/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/common.cpp.o
.PHONY : src/common/common.cpp.o

src/common/common.i: src/common/common.cpp.i
.PHONY : src/common/common.i

# target to preprocess a source file
src/common/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/common.cpp.i
.PHONY : src/common/common.cpp.i

src/common/common.s: src/common/common.cpp.s
.PHONY : src/common/common.s

# target to generate assembly for a file
src/common/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/common.cpp.s
.PHONY : src/common/common.cpp.s

src/common/console.o: src/common/console.cpp.o
.PHONY : src/common/console.o

# target to build an object file
src/common/console.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/console.cpp.o
.PHONY : src/common/console.cpp.o

src/common/console.i: src/common/console.cpp.i
.PHONY : src/common/console.i

# target to preprocess a source file
src/common/console.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/console.cpp.i
.PHONY : src/common/console.cpp.i

src/common/console.s: src/common/console.cpp.s
.PHONY : src/common/console.s

# target to generate assembly for a file
src/common/console.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/console.cpp.s
.PHONY : src/common/console.cpp.s

src/common/grammar-parser.o: src/common/grammar-parser.cpp.o
.PHONY : src/common/grammar-parser.o

# target to build an object file
src/common/grammar-parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/grammar-parser.cpp.o
.PHONY : src/common/grammar-parser.cpp.o

src/common/grammar-parser.i: src/common/grammar-parser.cpp.i
.PHONY : src/common/grammar-parser.i

# target to preprocess a source file
src/common/grammar-parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/grammar-parser.cpp.i
.PHONY : src/common/grammar-parser.cpp.i

src/common/grammar-parser.s: src/common/grammar-parser.cpp.s
.PHONY : src/common/grammar-parser.s

# target to generate assembly for a file
src/common/grammar-parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/grammar-parser.cpp.s
.PHONY : src/common/grammar-parser.cpp.s

src/common/sampling.o: src/common/sampling.cpp.o
.PHONY : src/common/sampling.o

# target to build an object file
src/common/sampling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/sampling.cpp.o
.PHONY : src/common/sampling.cpp.o

src/common/sampling.i: src/common/sampling.cpp.i
.PHONY : src/common/sampling.i

# target to preprocess a source file
src/common/sampling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/sampling.cpp.i
.PHONY : src/common/sampling.cpp.i

src/common/sampling.s: src/common/sampling.cpp.s
.PHONY : src/common/sampling.s

# target to generate assembly for a file
src/common/sampling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/sampling.cpp.s
.PHONY : src/common/sampling.cpp.s

src/common/train.o: src/common/train.cpp.o
.PHONY : src/common/train.o

# target to build an object file
src/common/train.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/train.cpp.o
.PHONY : src/common/train.cpp.o

src/common/train.i: src/common/train.cpp.i
.PHONY : src/common/train.i

# target to preprocess a source file
src/common/train.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/train.cpp.i
.PHONY : src/common/train.cpp.i

src/common/train.s: src/common/train.cpp.s
.PHONY : src/common/train.s

# target to generate assembly for a file
src/common/train.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/train.cpp.s
.PHONY : src/common/train.cpp.s

src/ggml-alloc.o: src/ggml-alloc.c.o
.PHONY : src/ggml-alloc.o

# target to build an object file
src/ggml-alloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml-alloc.c.o
.PHONY : src/ggml-alloc.c.o

src/ggml-alloc.i: src/ggml-alloc.c.i
.PHONY : src/ggml-alloc.i

# target to preprocess a source file
src/ggml-alloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml-alloc.c.i
.PHONY : src/ggml-alloc.c.i

src/ggml-alloc.s: src/ggml-alloc.c.s
.PHONY : src/ggml-alloc.s

# target to generate assembly for a file
src/ggml-alloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml-alloc.c.s
.PHONY : src/ggml-alloc.c.s

src/ggml-backend.o: src/ggml-backend.c.o
.PHONY : src/ggml-backend.o

# target to build an object file
src/ggml-backend.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml-backend.c.o
.PHONY : src/ggml-backend.c.o

src/ggml-backend.i: src/ggml-backend.c.i
.PHONY : src/ggml-backend.i

# target to preprocess a source file
src/ggml-backend.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml-backend.c.i
.PHONY : src/ggml-backend.c.i

src/ggml-backend.s: src/ggml-backend.c.s
.PHONY : src/ggml-backend.s

# target to generate assembly for a file
src/ggml-backend.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml-backend.c.s
.PHONY : src/ggml-backend.c.s

src/ggml-cuda.o: src/ggml-cuda.cu.o
.PHONY : src/ggml-cuda.o

# target to build an object file
src/ggml-cuda.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml-cuda.cu.o
.PHONY : src/ggml-cuda.cu.o

src/ggml-cuda.i: src/ggml-cuda.cu.i
.PHONY : src/ggml-cuda.i

# target to preprocess a source file
src/ggml-cuda.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml-cuda.cu.i
.PHONY : src/ggml-cuda.cu.i

src/ggml-cuda.s: src/ggml-cuda.cu.s
.PHONY : src/ggml-cuda.s

# target to generate assembly for a file
src/ggml-cuda.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml-cuda.cu.s
.PHONY : src/ggml-cuda.cu.s

src/ggml-quants.o: src/ggml-quants.c.o
.PHONY : src/ggml-quants.o

# target to build an object file
src/ggml-quants.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml-quants.c.o
.PHONY : src/ggml-quants.c.o

src/ggml-quants.i: src/ggml-quants.c.i
.PHONY : src/ggml-quants.i

# target to preprocess a source file
src/ggml-quants.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml-quants.c.i
.PHONY : src/ggml-quants.c.i

src/ggml-quants.s: src/ggml-quants.c.s
.PHONY : src/ggml-quants.s

# target to generate assembly for a file
src/ggml-quants.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml-quants.c.s
.PHONY : src/ggml-quants.c.s

src/ggml.o: src/ggml.c.o
.PHONY : src/ggml.o

# target to build an object file
src/ggml.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml.c.o
.PHONY : src/ggml.c.o

src/ggml.i: src/ggml.c.i
.PHONY : src/ggml.i

# target to preprocess a source file
src/ggml.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml.c.i
.PHONY : src/ggml.c.i

src/ggml.s: src/ggml.c.s
.PHONY : src/ggml.s

# target to generate assembly for a file
src/ggml.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ggml.dir/build.make CMakeFiles/ggml.dir/src/ggml.c.s
.PHONY : src/ggml.c.s

src/llama.o: src/llama.cpp.o
.PHONY : src/llama.o

# target to build an object file
src/llama.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama.dir/build.make CMakeFiles/llama.dir/src/llama.cpp.o
.PHONY : src/llama.cpp.o

src/llama.i: src/llama.cpp.i
.PHONY : src/llama.i

# target to preprocess a source file
src/llama.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama.dir/build.make CMakeFiles/llama.dir/src/llama.cpp.i
.PHONY : src/llama.cpp.i

src/llama.s: src/llama.cpp.s
.PHONY : src/llama.s

# target to generate assembly for a file
src/llama.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama.dir/build.make CMakeFiles/llama.dir/src/llama.cpp.s
.PHONY : src/llama.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... binding"
	@echo "... common"
	@echo "... ggml"
	@echo "... ggml_shared"
	@echo "... ggml_static"
	@echo "... llama"
	@echo "... llama_shared"
	@echo "... llama_static"
	@echo "... server"
	@echo "... src/common/common.o"
	@echo "... src/common/common.i"
	@echo "... src/common/common.s"
	@echo "... src/common/console.o"
	@echo "... src/common/console.i"
	@echo "... src/common/console.s"
	@echo "... src/common/grammar-parser.o"
	@echo "... src/common/grammar-parser.i"
	@echo "... src/common/grammar-parser.s"
	@echo "... src/common/sampling.o"
	@echo "... src/common/sampling.i"
	@echo "... src/common/sampling.s"
	@echo "... src/common/train.o"
	@echo "... src/common/train.i"
	@echo "... src/common/train.s"
	@echo "... src/ggml-alloc.o"
	@echo "... src/ggml-alloc.i"
	@echo "... src/ggml-alloc.s"
	@echo "... src/ggml-backend.o"
	@echo "... src/ggml-backend.i"
	@echo "... src/ggml-backend.s"
	@echo "... src/ggml-cuda.o"
	@echo "... src/ggml-cuda.i"
	@echo "... src/ggml-cuda.s"
	@echo "... src/ggml-quants.o"
	@echo "... src/ggml-quants.i"
	@echo "... src/ggml-quants.s"
	@echo "... src/ggml.o"
	@echo "... src/ggml.i"
	@echo "... src/ggml.s"
	@echo "... src/llama.o"
	@echo "... src/llama.i"
	@echo "... src/llama.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

